const LANES = [
  { key: "top", label: "TOP" },
  { key: "jungle", label: "JG" },
  { key: "mid", label: "MID" },
  { key: "adc", label: "BOT" },
  { key: "support", label: "SUP" }
];

const SIDES = [
  { key: "blue", label: "青サイド" },
  { key: "red", label: "赤サイド" }
];

const CHAMPION_MASTER = {
  Aatrox: { id: "Aatrox", name: "Aatrox", ja: "エイトロックス" },
  Ahri: { id: "Ahri", name: "Ahri", ja: "アーリ" },
  Akali: { id: "Akali", name: "Akali", ja: "アカリ" },
  Akshan: { id: "Akshan", name: "Akshan", ja: "アクシャン" },
  Alistar: { id: "Alistar", name: "Alistar", ja: "アリスター" },
  Ambessa: { id: "Ambessa", name: "Ambessa", ja: "アンベッサ" },
  Amumu: { id: "Amumu", name: "Amumu", ja: "アムム" },
  Anivia: { id: "Anivia", name: "Anivia", ja: "アニビア" },
  Annie: { id: "Annie", name: "Annie", ja: "アニー" },
  Aphelios: { id: "Aphelios", name: "Aphelios", ja: "アフェリオス" },
  Ashe: { id: "Ashe", name: "Ashe", ja: "アッシュ" },
  AurelionSol: { id: "AurelionSol", name: "Aurelion Sol", ja: "オレリオン・ソル" },
  Aurora: { id: "Aurora", name: "Aurora", ja: "オーロラ" },
  Azir: { id: "Azir", name: "Azir", ja: "アジール" },
  Bard: { id: "Bard", name: "Bard", ja: "バード" },
  Belveth: { id: "Belveth", name: "Bel'Veth", ja: "ベル＝ヴェス" },
  Blitzcrank: { id: "Blitzcrank", name: "Blitzcrank", ja: "ブリッツクランク" },
  Brand: { id: "Brand", name: "Brand", ja: "ブランド" },
  Braum: { id: "Braum", name: "Braum", ja: "ブラウム" },
  Briar: { id: "Briar", name: "Briar", ja: "ブライアー" },
  Caitlyn: { id: "Caitlyn", name: "Caitlyn", ja: "ケイトリン" },
  Camille: { id: "Camille", name: "Camille", ja: "カミール" },
  Cassiopeia: { id: "Cassiopeia", name: "Cassiopeia", ja: "カシオペア" },
  Chogath: { id: "Chogath", name: "Cho'Gath", ja: "チョ＝ガス" },
  Corki: { id: "Corki", name: "Corki", ja: "コーキ" },
  Darius: { id: "Darius", name: "Darius", ja: "ダリウス" },
  Diana: { id: "Diana", name: "Diana", ja: "ダイアナ" },
  Draven: { id: "Draven", name: "Draven", ja: "ドレイブン" },
  DrMundo: { id: "DrMundo", name: "Dr. Mundo", ja: "ドクター・ムンド" },
  Ekko: { id: "Ekko", name: "Ekko", ja: "エコー" },
  Elise: { id: "Elise", name: "Elise", ja: "エリス" },
  Evelynn: { id: "Evelynn", name: "Evelynn", ja: "イブリン" },
  Ezreal: { id: "Ezreal", name: "Ezreal", ja: "エズリアル" },
  Fiddlesticks: { id: "Fiddlesticks", name: "Fiddlesticks", ja: "フィドルスティックス" },
  Fiora: { id: "Fiora", name: "Fiora", ja: "フィオラ" },
  Fizz: { id: "Fizz", name: "Fizz", ja: "フィズ" },
  Galio: { id: "Galio", name: "Galio", ja: "ガリオ" },
  Gangplank: { id: "Gangplank", name: "Gangplank", ja: "ガングプランク" },
  Garen: { id: "Garen", name: "Garen", ja: "ガレン" },
  Gnar: { id: "Gnar", name: "Gnar", ja: "ナー" },
  Gragas: { id: "Gragas", name: "Gragas", ja: "グラガス" },
  Graves: { id: "Graves", name: "Graves", ja: "グレイブス" },
  Gwen: { id: "Gwen", name: "Gwen", ja: "グウェン" },
  Hecarim: { id: "Hecarim", name: "Hecarim", ja: "ヘカリム" },
  Heimerdinger: { id: "Heimerdinger", name: "Heimerdinger", ja: "ハイマー・ディンガー" },
  Hwei: { id: "Hwei", name: "Hwei", ja: "フェイ" },
  Illaoi: { id: "Illaoi", name: "Illaoi", ja: "イラオイ" },
  Irelia: { id: "Irelia", name: "Irelia", ja: "イレリア" },
  Ivern: { id: "Ivern", name: "Ivern", ja: "アイバーン" },
  Janna: { id: "Janna", name: "Janna", ja: "ジャンナ" },
  JarvanIV: { id: "JarvanIV", name: "Jarvan IV", ja: "ジャーヴァンⅣ" },
  Jax: { id: "Jax", name: "Jax", ja: "ジャックス" },
  Jayce: { id: "Jayce", name: "Jayce", ja: "ジェイス" },
  Jhin: { id: "Jhin", name: "Jhin", ja: "ジン" },
  Jinx: { id: "Jinx", name: "Jinx", ja: "ジンクス" },
  Kaisa: { id: "Kaisa", name: "Kai'Sa", ja: "カイ＝サ" },
  Kalista: { id: "Kalista", name: "Kalista", ja: "カリスタ" },
  Karma: { id: "Karma", name: "Karma", ja: "カルマ" },
  Karthus: { id: "Karthus", name: "Karthus", ja: "カーサス" },
  Kassadin: { id: "Kassadin", name: "Kassadin", ja: "カサディン" },
  Katarina: { id: "Katarina", name: "Katarina", ja: "カタリナ" },
  Kayle: { id: "Kayle", name: "Kayle", ja: "ケイル" },
  Kayn: { id: "Kayn", name: "Kayn", ja: "ケイン" },
  Kennen: { id: "Kennen", name: "Kennen", ja: "ケネン" },
  Khazix: { id: "Khazix", name: "Kha'Zix", ja: "カ＝ジックス" },
  Kindred: { id: "Kindred", name: "Kindred", ja: "キンドレッド" },
  Kled: { id: "Kled", name: "Kled", ja: "クレッド" },
  KogMaw: { id: "KogMaw", name: "Kog'Maw", ja: "コグ＝マウ" },
  KSante: { id: "KSante", name: "K'Sante", ja: "カ・サンテ" },
  Leblanc: { id: "Leblanc", name: "LeBlanc", ja: "ルブラン" },
  LeeSin: { id: "LeeSin", name: "Lee Sin", ja: "リー・シン" },
  Leona: { id: "Leona", name: "Leona", ja: "レオナ" },
  Lillia: { id: "Lillia", name: "Lillia", ja: "リリア" },
  Lissandra: { id: "Lissandra", name: "Lissandra", ja: "リサンドラ" },
  Lucian: { id: "Lucian", name: "Lucian", ja: "ルシアン" },
  Lulu: { id: "Lulu", name: "Lulu", ja: "ルル" },
  Lux: { id: "Lux", name: "Lux", ja: "ラックス" },
  Malphite: { id: "Malphite", name: "Malphite", ja: "マルファイト" },
  Malzahar: { id: "Malzahar", name: "Malzahar", ja: "マルザハール" },
  Maokai: { id: "Maokai", name: "Maokai", ja: "マオカイ" },
  MasterYi: { id: "MasterYi", name: "Master Yi", ja: "マスター・イー" },
  Mel: { id: "Mel", name: "Mel", ja: "メル" },
  Milio: { id: "Milio", name: "Milio", ja: "ミリオ" },
  MissFortune: { id: "MissFortune", name: "Miss Fortune", ja: "ミス・フォーチュン" },
  Mordekaiser: { id: "Mordekaiser", name: "Mordekaiser", ja: "モルデカイザー" },
  Morgana: { id: "Morgana", name: "Morgana", ja: "モルガナ" },
  Naafiri: { id: "Naafiri", name: "Naafiri", ja: "ナフィーリ" },
  Nami: { id: "Nami", name: "Nami", ja: "ナミ" },
  Nasus: { id: "Nasus", name: "Nasus", ja: "ナサス" },
  Nautilus: { id: "Nautilus", name: "Nautilus", ja: "ノーチラス" },
  Neeko: { id: "Neeko", name: "Neeko", ja: "ニーコ" },
  Nidalee: { id: "Nidalee", name: "Nidalee", ja: "ニダリー" },
  Nilah: { id: "Nilah", name: "Nilah", ja: "ニーラ" },
  Nocturne: { id: "Nocturne", name: "Nocturne", ja: "ノクターン" },
  Nunu: { id: "Nunu", name: "Nunu & Willump", ja: "ヌヌ＆ウィルンプ" },
  Olaf: { id: "Olaf", name: "Olaf", ja: "オラフ" },
  Orianna: { id: "Orianna", name: "Orianna", ja: "オリアナ" },
  Ornn: { id: "Ornn", name: "Ornn", ja: "オーン" },
  Pantheon: { id: "Pantheon", name: "Pantheon", ja: "パンテオン" },
  Poppy: { id: "Poppy", name: "Poppy", ja: "ポッピー" },
  Pyke: { id: "Pyke", name: "Pyke", ja: "パイク" },
  Qiyana: { id: "Qiyana", name: "Qiyana", ja: "キヤナ" },
  Quinn: { id: "Quinn", name: "Quinn", ja: "クイン" },
  Rakan: { id: "Rakan", name: "Rakan", ja: "ラカン" },
  Rammus: { id: "Rammus", name: "Rammus", ja: "ラムス" },
  RekSai: { id: "RekSai", name: "Rek'Sai", ja: "レク＝サイ" },
  Rell: { id: "Rell", name: "Rell", ja: "レル" },
  Renata: { id: "Renata", name: "Renata Glasc", ja: "レナータ・グラスク" },
  Renekton: { id: "Renekton", name: "Renekton", ja: "レネクトン" },
  Rengar: { id: "Rengar", name: "Rengar", ja: "レンガー" },
  Riven: { id: "Riven", name: "Riven", ja: "リヴェン" },
  Rumble: { id: "Rumble", name: "Rumble", ja: "ランブル" },
  Ryze: { id: "Ryze", name: "Ryze", ja: "ライズ" },
  Samira: { id: "Samira", name: "Samira", ja: "サミーラ" },
  Sejuani: { id: "Sejuani", name: "Sejuani", ja: "セジュアニ" },
  Senna: { id: "Senna", name: "Senna", ja: "セナ" },
  Seraphine: { id: "Seraphine", name: "Seraphine", ja: "セラフィーン" },
  Sett: { id: "Sett", name: "Sett", ja: "セト" },
  Shaco: { id: "Shaco", name: "Shaco", ja: "シャコ" },
  Shen: { id: "Shen", name: "Shen", ja: "シェン" },
  Shyvana: { id: "Shyvana", name: "Shyvana", ja: "シヴァーナ" },
  Singed: { id: "Singed", name: "Singed", ja: "シンジド" },
  Sion: { id: "Sion", name: "Sion", ja: "サイオン" },
  Sivir: { id: "Sivir", name: "Sivir", ja: "シヴィア" },
  Skarner: { id: "Skarner", name: "Skarner", ja: "スカーナー" },
  Smolder: { id: "Smolder", name: "Smolder", ja: "スモルダー" },
  Sona: { id: "Sona", name: "Sona", ja: "ソナ" },
  Soraka: { id: "Soraka", name: "Soraka", ja: "ソラカ" },
  Swain: { id: "Swain", name: "Swain", ja: "スウェイン" },
  Sylas: { id: "Sylas", name: "Sylas", ja: "サイラス" },
  Syndra: { id: "Syndra", name: "Syndra", ja: "シンドラ" },
  TahmKench: { id: "TahmKench", name: "Tahm Kench", ja: "タム・ケンチ" },
  Taliyah: { id: "Taliyah", name: "Taliyah", ja: "タリヤ" },
  Talon: { id: "Talon", name: "Talon", ja: "タロン" },
  Taric: { id: "Taric", name: "Taric", ja: "タリック" },
  Teemo: { id: "Teemo", name: "Teemo", ja: "ティーモ" },
  Thresh: { id: "Thresh", name: "Thresh", ja: "スレッシュ" },
  Tristana: { id: "Tristana", name: "Tristana", ja: "トリスターナ" },
  Trundle: { id: "Trundle", name: "Trundle", ja: "トランドル" },
  Tryndamere: { id: "Tryndamere", name: "Tryndamere", ja: "トリンダメア" },
  TwistedFate: { id: "TwistedFate", name: "Twisted Fate", ja: "ツイステッド・フェイト" },
  Twitch: { id: "Twitch", name: "Twitch", ja: "トゥイッチ" },
  Udyr: { id: "Udyr", name: "Udyr", ja: "ウディア" },
  Urgot: { id: "Urgot", name: "Urgot", ja: "アーゴット" },
  Varus: { id: "Varus", name: "Varus", ja: "ヴァルス" },
  Vayne: { id: "Vayne", name: "Vayne", ja: "ヴェイン" },
  Veigar: { id: "Veigar", name: "Veigar", ja: "ベイガー" },
  Velkoz: { id: "Velkoz", name: "Vel'Koz", ja: "ヴェル＝コズ" },
  Vex: { id: "Vex", name: "Vex", ja: "ヴェックス" },
  Vi: { id: "Vi", name: "Vi", ja: "ヴァイ" },
  Viego: { id: "Viego", name: "Viego", ja: "ヴィエゴ" },
  Viktor: { id: "Viktor", name: "Viktor", ja: "ビクター" },
  Vladimir: { id: "Vladimir", name: "Vladimir", ja: "ブラッドミア" },
  Volibear: { id: "Volibear", name: "Volibear", ja: "ボリベア" },
  Warwick: { id: "Warwick", name: "Warwick", ja: "ワーウィック" },
  MonkeyKing: { id: "MonkeyKing", name: "Wukong", ja: "ウーコン" },
  Xayah: { id: "Xayah", name: "Xayah", ja: "ザヤ" },
  Xerath: { id: "Xerath", name: "Xerath", ja: "ゼラス" },
  XinZhao: { id: "XinZhao", name: "Xin Zhao", ja: "シン・ジャオ" },
  Yasuo: { id: "Yasuo", name: "Yasuo", ja: "ヤスオ" },
  Yone: { id: "Yone", name: "Yone", ja: "ヨネ" },
  Yorick: { id: "Yorick", name: "Yorick", ja: "ヨリック" },
  Yuumi: { id: "Yuumi", name: "Yuumi", ja: "ユーミ" },
  Yunara: { id: "Yunara", name: "Yunara", ja: "ユナラ" },
  Zac: { id: "Zac", name: "Zac", ja: "ザック" },
  Zed: { id: "Zed", name: "Zed", ja: "ゼド" },
  Zeri: { id: "Zeri", name: "Zeri", ja: "ゼリ" },
  Ziggs: { id: "Ziggs", name: "Ziggs", ja: "ジグス" },
  Zilean: { id: "Zilean", name: "Zilean", ja: "ジリアン" },
  Zoe: { id: "Zoe", name: "Zoe", ja: "ゾーイ" },
  Zyra: { id: "Zyra", name: "Zyra", ja: "ザイラ" }
};

const CHAMPION_POOL_IDS = {
  top: [
    "Yone", "Vayne", "Yasuo", "Mordekaiser", "Yorick", "Aatrox", "Sett", "Malphite", "XinZhao", "Garen",
    "Ornn", "Akali", "Sion", "Pantheon", "Jax", "Zac", "Shen", "Irelia", "Darius", "Rumble",
    "Gangplank", "Chogath", "TahmKench", "Renekton", "Nasus", "Volibear", "DrMundo", "Ambessa", "Jayce", "Illaoi",
    "Fiora", "Gragas", "KSante", "Gwen", "Kennen", "Heimerdinger", "Urgot", "Olaf", "Camille", "Kled",
    "Kayle", "Singed", "Teemo", "Trundle", "Tryndamere", "Gnar", "Riven", "LeeSin", "Shyvana", "Rengar", "Udyr"
  ],
  jungle: [
    "MasterYi", "Diana", "Sylas", "XinZhao", "Naafiri", "Jax", "Viego", "Nocturne", "Lillia", "Evelynn",
    "JarvanIV", "Graves", "Shyvana", "Ambessa", "LeeSin", "Rengar", "Briar", "Skarner", "Karthus", "Nunu",
    "Talon", "Ivern", "Amumu", "Vi", "MonkeyKing", "Udyr", "Ekko", "Elise", "Khazix", "Kindred",
    "Quinn", "Kayn", "Zac", "Shaco", "Sejuani", "Zed", "Nidalee", "Fiddlesticks", "Hecarim", "Belveth",
    "Rammus", "RekSai", "Warwick"
  ],
  mid: [
    "Yone", "Ahri", "Xerath", "Diana", "Yasuo", "Mel", "Sylas", "Lux", "Veigar", "Orianna",
    "Akali", "Naafiri", "Viktor", "Hwei", "Irelia", "Vex", "Syndra", "TwistedFate", "Cassiopeia", "Aurora",
    "Leblanc", "Fizz", "Malzahar", "Zoe", "Lissandra", "Kassadin", "Vladimir", "Taliyah", "Katarina", "Anivia",
    "Talon", "AurelionSol", "Ryze", "Akshan", "Azir", "Annie", "Ekko", "Galio", "Qiyana", "Zed"
  ],
  adc: [
    "Ashe", "MissFortune", "Jinx", "Caitlyn", "Varus", "Jhin", "Ezreal", "Yunara", "Lucian", "Kaisa",
    "Smolder", "Aphelios", "Sivir", "Tristana", "Vayne", "Xayah", "Ziggs", "Samira", "Senna", "Twitch",
    "Draven", "Nilah", "Zeri", "Corki", "KogMaw", "Kalista"
  ],
  support: [
    "Xerath", "Mel", "Lux", "Seraphine", "Velkoz", "Pyke", "Leona", "Pantheon", "Morgana", "Thresh",
    "Milio", "Sona", "Senna", "Nautilus", "TahmKench", "Brand", "Poppy", "Nami", "Rell", "Blitzcrank",
    "Swain", "Karma", "Taric", "Maokai", "Zilean", "Yuumi", "Zyra", "Alistar", "Janna", "Soraka",
    "Neeko", "Bard", "Braum", "Rakan", "Lulu", "Renata"
  ]
};

const ENCHANTER_IDS = [
  "Karma", "Janna", "Zilean", "Senna", "Seraphine", "Sona",
  "Soraka", "Taric", "Nami", "Milio", "Lulu", "Renata"
];

const CHAMPION_POOLS = Object.fromEntries(
  Object.entries(CHAMPION_POOL_IDS).map(([lane, ids]) => [
    lane,
    ids.map((id, index) => ({
      ...CHAMPION_MASTER[id],
      weight: 1
    }))
  ])
);
